### ISSUE TITLE
Compilation error when creating gsl::span<const T*> from std::vector<T*>

### ISSUE THREAD

**Issue by HuguesDelorme** [Microsoft/GSL#734] opened 2018-09-13 14:55 UTC
Visual C++ 2017 fails to compile this simple (dummy) code  :
`    std::vector<int*> vec;`
`    gsl::span<const int*> spanVec = vec;`
Error : C2440 Impossible to convert `std::vector<int*, std::allocator<_Ty>>` to `gsl::span<const int*, -1>`

Whereas it compiles fine when creating from an std::array<int*> :
`    std::array<int*, 10> array;`
`    gsl::span<const int*> spanArray = array;`

Why this compilation error with std::vector<int*> ?

**Comment by beinhaerter** [comment] 2018-09-19 19:35
Which compiler version and which GSL version did you test with?

On my VC 15.8.4 and GSL v2.0.0 both versions do not compile. Error for the array variant is:

> 1>...\gsl\include\gsl\span(400): error C2664: 'gsl::span<const int *,-1>::storage_type<gsl::details::extent_type<-1>>::storage_type(gsl::span<const int *,-1>::storage_type<gsl::details::extent_type<-1>> &&)': cannot convert argument 1 from '_Ty *' to 'gsl::span<const int *,-1>::KnownNotNull'
> 1>        with
> 1>        [
> 1>            _Ty=int *
> 1>        ]
> 1>...\gsl\include\gsl\span(401): note: No constructor could take the source type, or constructor overload resolution was ambiguous
> 1>issue734.cpp(15): note: see reference to function template instantiation 'gsl::span<const int *,-1>::span<10,int*>(std::array<int *,10> &) noexcept' being compiled
> 1>issue734.cpp(15): note: see reference to function template instantiation 'gsl::span<const int *,-1>::span<10,int*>(std::array<int *,10> &) noexcept' being compiled

**Comment by annagrin** [comment] 2018-11-06 19:07
The conversion should not allowed by any compiler - this is due to pointer conversion, which is in your case `int **` to `const int **`. I couldn't reproduce your example of creation of span from std::array compiling, please let me know what version of msvc you are using.

```
    int ** pp;
    const int**  cpp = pp; // does not compile
```

```
    std::vector<int*> v{ nullptr };
    gsl::span<const int*> spv = v; // does not compile 
    std::vector<const int*> sv = v; // does not compile
```

```
    std::array<int*, 1> arr{nullptr};
    gsl::span<const int*> sarr = arr; // does not compile
```

To compile, you want a conversion to `const int * const*` :

`  gsl::span<const int* const> spv2 = v; // compiles`

For explanation, see the answer half-way down with 34 votes on it (thanks @neilmacintosh for finding it!) there:

[Why isn't it legal to convert “pointer to pointer to non-const” to a “pointer to pointer to const”](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F2220916%2Fwhy-isnt-it-legal-to-convert-pointer-to-pointer-to-non-const-to-a-pointer-to&amp;data=02%7C01%7Cannagrin%40microsoft.com%7C0903b85859554a1ef09308d64418700c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636771269095905864&amp;sdata=9s61JbBrac5ZK4u%2Fp8VtacEhbQZVZ4381EhFIChXbww%3D&amp;reserved=0)

**Comment by annagrin** [comment] 2018-11-06 19:12
Closing this, @HuguesDelorme  please reopen if you find an example that compiles illegally.

**Closed by annagrin** 2018-11-06 19:12 UTC
