### ISSUE TITLE
Name conflict with the GNU Scientific Library

### ISSUE THREAD

**Issue by mapreri** [Microsoft/GSL#466] opened 2017-03-12 17:41 UTC
Microsoft/GSL conflicts with https://www.gnu.org/software/gsl/ (another completely different project) and not only with the name, but as far as I can see also in the installed files.

Would it be possible to ponder a rename of this project, on the basis that GNU's GSL is much older than Microsoft's GSL?

**Comment by infinity0** [comment] 2017-03-12 17:44
GSL has been around since 1996 https://www.gnu.org/software/gsl/ and is packaged in all the popular FOSS OS distros that I checked:

https://admin.fedoraproject.org/pkgdb/package/rpms/gsl/
https://packages.debian.org/search?keywords=gsl
https://www.archlinux.org/packages/extra/i686/gsl/
https://packages.gentoo.org/packages/sci-libs/gsl
http://portsmon.freebsd.org/portoverview.py?category=math&portname=gsl
ftp://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/math/gsl/README.html
http://ports.su/devel/gsl
https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/gsl
https://www.gnu.org/software/guix/packages/g.html

**Comment by maikel** [comment] 2017-03-12 17:47
This is one of the earliest issues https://github.com/Microsoft/GSL/issues/31 and have already been in detail. Concrete conflicts would help, I guess.

**Comment by infinity0** [comment] 2017-03-12 17:53
> We can't avoid conflicts with every other thing out there, so we will stick with something sensible for this library.

In fact, it is possible to "avoid conflicts" by using google.com. Not sure if bing.com makes it as easy to find these public conflicts, however. GNU Scientific Library is not some random small library nobody uses, like the [Go vs Go! conflict](https://github.com/golang/go/issues/9), it is the #1 result on Google for "GSL", the #2 result being Global Starcraft League.

**Comment by neilmacintosh** [comment] 2017-03-12 18:46
@maikel has correctly identified that we have already discussed this issue. My position has not chnaged, so there is nothing to be done here and I am closing the issue.

To summarize:

1. Two projects sharing the same three letter acronym as a short-form name is not a conflict I am going to worry about. Most people can distinguish which one is being discussed via context. If not, then qualify appropriately (as I do in this response).

2. Namespaces are the pre-existing conflict-resolution mechanism in C++. GNU Scientific Library is a C library and so does not share the same namespace as Guideline Support Library in a C++ program. If you want to use the two in the same program, then just use namespaces appropriately. 

3. There is no file conflict between the libraries. GNU Scientific Library uses a `.h` suffix for its files, Guideline Support Library does not. Also, I'm pretty sure there are a bunch of header names that are wildly different (I do not think we have, or will ever have a `gsl_sf_bessel.h` in the Guideline Support Library).

**Closed by neilmacintosh** 2017-03-12 18:46 UTC

**Comment by infinity0** [comment] 2017-03-12 22:14
The main problem is the include path, it's very confusing to install both MS-GSL and GSL into `/usr/include/gsl`, even if no files are directly conflicting today. I don't think any distribution is going to want to do that. I was going to suggest `/usr/include/c++/gsl` as an alternative path for Debian and probably other FOSS distributions, but it would be good to get an agreed standard on this alternative path from you the upstream project.

Then, as mentioned in the other thread, there is the potential problem of GSL C++ wrappers wanting to use, or already using, the `gsl` C++ namespace. I have no solution for this, and I haven't looked at the existing wrappers yet. Does something like

~~~~
namespace std {
#include <c++/gsl/gsl>
}
~~~~

work to rename namespaces in C++?

**Comment by MikeGitb** [comment] 2017-03-12 22:28
Nope, that's wrong for so many reasons (mainly because you are also putting any indirectly included header files into the new namespace). 

And yes, there are gnusl wrappers out there that use the gsl namespace (although the ones I know of seem to be no longer maintained). 

:(

**Comment by galik** [comment] 2017-03-12 23:40
I think this question is going to come up again and again as more people adopt CppCoreGuidelines, particularly in the educational and scientific communities where GNU GSL gets used a lot.

The fact that GNU GSL is a C library does not detract from its occupying the "gsl" namespace imo because namespaces are *conceptual*. Just because `C++` has the `namespace` keyword doesn't give it special privileges there.

In `C` the namespace is usually expressed using function prefixes like
```cpp
auto v = gsl_acosh(GSL_CONST_CGSM_BOHR_RADIUS);
```
The fact that GNU GSL uses that convention seems to me a reasonable "claim" on the "gsl" namespace and the natural expression of that in `C++` is by using `namespace gsl {}`.

If that project (or an off-shoot) were to create `C++` wrappers it will find its current namespace taken.

And apart from that people using both libraries are going to wonder what they mean by "GSL" because it is not like writing scientific programs is mutually exclusive from using the `CppCoreGuidelines`. Hopefully we want scientists and those in education to use the `CppCoreGuidelines` just as much as everyone else.

Even more so if they're building rockets...

**Comment by neilmacintosh** [comment] 2017-03-13 18:25
@galik if it does, then each question will get redirected to the existing answers :-) (though maybe this is a good prompt for me to go create a FAQ).

A function prefix is not the same thing as a namespace. If GNU GSL decides to add C++ wrappers AND decides to use just "gsl" as their namespace , then it will face two choices:

1. Use it anyway and let users rely on language facilities to resolve namespace conflicts in their code (these exist - namespaces are not expected to be universally unique). Seems reasonable to me.
2. Choose something else. Seems reasonable to me.

Regarding people wondering what is meant by "GSL". It still seems very easy to me to distinguish between GSL the scientific computation library and GSL the foundational types library in conversation/discussion. There are a bunch of ways to do so...none seem particularly difficult.

**Comment by MikeGitb** [comment] 2017-03-14 07:47
> Use it anyway and let users rely on language facilities to resolve namespace conflicts in their code (these exist - namespaces are not expected to be universally unique). Seems reasonable to me.

That is now the second time I hear about such language facilities. Could you shortly explain what you mean or point me to some source about such techniques?

**Comment by galik** [comment] 2017-03-14 20:55
Perhaps it would be a good idea to make `MS GSL`'s `namespace` user configurable in the *install* script?

Inevitably `Linux` distros are going to want to create a package for the `MS GSL`. The installation *package name* for `GNU GSL` is simply "gsl".

Also in many `Linux` distributions and other `OSs` that use `GNU` tools, the library and header file discovery is achieved using the `pkg-config` tool. Currently the `GNU GSL` is queried like this:
```make
CXXFLAGS += $(shell pkg-config gsl --cflags)
LDFLAGS += $(shell pkg-config gsl --libs)
```

Linux distributors will need to pick a different name to "gsl" for things like *package name*, the colliding `include` folder, the `pkg-config` tag and maybe other things I didn't think of. 

It may be that `Linux` distros will simply create a `patch` for `MS GSL` to change its folder name and the namespace. Making the namespace *user configurable* would make that less painful.

**Comment by neilmacintosh** [comment] 2017-03-14 21:00
@MikeGitb The MSVC documentation at: https://docs.microsoft.com/en-us/cpp/cpp/namespaces-cpp covers the language facilities. In particular, namespace qualification is the simplest way to disambiguate. Using declarations and namespace aliases can also be helpful if you have to resolve conflicts.

@galik I'm not going to make the namespace configurable. We chose `gsl` and we'll stick with it.

Roll on modules... ;-)

**Comment by MikeGitb** [comment] 2017-03-15 23:44
Sorry, I still don't get it. Just to make sure we are talking about the same thing:

	//libA.h
	namespace foo {
	    struct Bar { int i; int b; };
	}

	//libB.h
	namespace foo {
	    struct Bar { std::string name; int cnt; };
	}

	//app.cpp
	#include "libA.h"
	#include "libB.h" //compiler error

How does namespace qualification help when the namespace is the same for both libraries? I also don't see how aliases would help. In fact, the link you gave talks about using long and unambigous namespaces and then let the user create shorter aliases for convenience on a case-by-case basis.

**Comment by gdr-at-ms** [comment] 2017-03-15 23:51
Is this what actually is happening?  Or are we imagining what might happen?

**Comment by galik** [comment] 2017-03-16 00:33
> @gdr-at-ms  Is this what actually is happening? Or are we imagining what might happen?

It is not unrealistic that it could happen. `GNU GSL` is not an insignificant library.

**Comment by MikeGitb** [comment] 2017-03-16 00:34
@gdr-at-ms: My interest is purely technical: Neilmacintosh said

> let users rely on language facilities to resolve namespace conflicts in their code (these exist - namespaces are not expected to be universally unique).

As I'm not aware of any mechanism that would allow me to resolve a namespace conflict I'm eager to learn about it (c++ keeps surprising me).

The question of whether there exists a namespace conflict: Yes, both galik and I have given examples of open source gnusl c++ wrapper libraries that use the gsl namespace. Whether they are important enough to worry about is your decision (as I said, both projects look abandoned to me) and it is clear what that decision is, so I see no point in arguing about it (incidentally I'm on your side any way).

That the reuse of the gsl abbreviation in folder and library names can lead to all kinds of other inconveniences has also be explained - again, it is on you to decide if those bother you or not.

Personally I do think this situation should have (and could have) been avoided from the beginning, but now it is probably simply too late to rename the gsl.

**Comment by gdr-at-ms** [comment] 2017-03-16 00:37
@galik Understood. Just trying to clarify what the issue is here.

@MikeGitb I looked at your example, and I'm trying to understand whether there is actual collision of `foo::bar`s, not trying to pass a judgment of importance of library A vs. library B.

**Comment by galik** [comment] 2017-03-16 00:38
> @MikeGitb In fact, the link you gave talks about using long and unambigous namespaces and then let the user create shorter aliases for convenience on a case-by-case basis.

I provided a similar argument to avoid this exact problem in another thread where we discussed this.

Here: https://github.com/Microsoft/GSL/issues/31#issuecomment-249472358

And here: https://github.com/Microsoft/GSL/issues/31#issuecomment-249473893

**Comment by MikeGitb** [comment] 2017-03-16 08:14
@gdr-at-ms: Sorry if I missunderstand you again, but yes - in my example you would get a compiler error about redefinition of `foo::Bar` (https://godbolt.org/g/K8KSca). 

Just as neil I also don't expect to see any actual name collisions or ambiguous overload resolutions when bringing one of the wrapper libraries and the gsl into the same project (but I haven't actually checked myself). As I said, my interest is purely technical.

The only thing I would find troublesome is if one had to write #include <c++/gsl/gsl> on Linux (as indicated by infinity0) and #include <gsl/gsl> on windows if one wants to use the system / packet manager provided version of the gsl. But I don't know enough about Linux conventions to know it there really isn't a way around this,

**Comment by gdr-at-ms** [comment] 2017-03-16 10:57
@MikeGitb You misunderstood my question. I am not looking for the hypotheticals.  I would like to know if there are actual conflicts of types from this GSL and the other GSL, as you were trying to abstractly illustrate in several messages up.

**Comment by MikeGitb** [comment] 2017-03-16 21:11
Ok, sorry for that.

Then to quote myself: 

> Just as neil I also don't expect to see any actual name collisions or ambiguous overload resolutions when bringing one of the wrapper libraries and the gsl into the same project (but I haven't actually checked myself). 

The entire reason I chimed in originally was that neilmacintosh hinted at language facilities I was not aware of but eager to learn about:
>>    Use it anyway and **let users rely on language facilities to resolve namespace conflicts in their code** (these exist - namespaces are not expected to be universally unique). Seems reasonable to me. 
   
> That is now the second time I hear about such language facilities. Could you shortly explain what you mean or point me to some source about such techniques?

As I didn't understand how the information on the linked website could be used to resolve namespace conflicts I presented the abstract example to make sure neil and I were talking about the same thing and I had not simply misunderstood his original statement.

At no point did I want to imply that using the gsl and some gnusl related library in the same project would currently lead to actual compilation errors. I just said that there are other libraries out there that use the same namespace.  But as I'm using neither the gsl nor the gnusl library, I don't care enough to  investigate if there will any actual name clashes (as I said before, I don't expect any).

**Comment by gdr-at-ms** [comment] 2017-03-16 21:24
@MikeGitb Thanks for clarifying.

**Comment by thesamesam** [comment] 2025-04-15 22:11
For what it's worth, the collision is real in the case where someone passes `-I/usr/include/gsl` (as GNU gsl requires) to the compiler, because `<algorithm>` now gets resolved to ms-gsl's copy, then one gets gunk like:
```
/usr/include/gsl/algorithm: In function void gsl::copy(gsl::span<ElementType, FirstExtent>, gsl::span<DestElementType, DestExtent>)’:
/usr/include/gsl/algorithm:54:10: error: copy_n’ is not a member of std’; did you mean copy’?
   54 |     std::copy_n(src.data(), src.size(), dest.data());
      |          ^~~~~~
```
