### ISSUE TITLE
gsl/gsl

### ISSUE THREAD

**Issue by Zari65** [Microsoft/GSL#643] opened 2018-03-17 04:03 UTC
https://github.com/Microsoft/GSL/blob/d846fe50a3f0bb7767c7e087a05f4be95f4da0ec/GSL.natvis#L98

**Comment by beinhaerter** [comment] 2018-03-17 13:42
@Zari65 Can you please elaborate!? At least for me neither the title nor the linked line in GSL.natvis are sufficient to understand what the issue is.

**Comment by annagrin** [comment] 2019-01-18 21:00
closing since there is no clarification

**Closed by annagrin** 2019-01-18 21:00 UTC
