### ISSUE TITLE
template with C linkage build errors 

### ISSUE THREAD

**Issue by zaq32** [microsoft/GSL#843] opened 2020-02-03 11:22 UTC
When GSL v2.1.0 is embedded as a dependency in a cmake project and compiled with arm-none-eabi gcc (8.3.1 in my case) following errors are being generated in huge quantities:

```
x:\src\toolchain\arm-none-eabi\include\c++\8.3.1\new:194:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
x:\src\toolchain\arm-none-eabi\include\c++\8.3.1\new:202:3: error: template with C linkage
   template<typename _Ret, typename... _Args _GLIBCXX_NOEXCEPT_PARM>
   ^~~~~~~~
x:\src\toolchain\arm-none-eabi\include\c++\8.3.1\new:204:3: error: template with C linkage
   template<typename _Ret, typename... _Args _GLIBCXX_NOEXCEPT_PARM>
   ^~~~~~~~
x:\src\toolchain\arm-none-eabi\include\c++\8.3.1\new:208:8: error: conflicting declaration of C function 'void std::launder(const void*)'
   void launder(const void*) = delete;
        ^~~~~~~
x:\src\toolchain\arm-none-eabi\include\c++\8.3.1\new:207:8: note: previous declaration 'void std::launder(void*)'
   void launder(void*) = delete;
```
Full build log: [build.log](https://github.com/microsoft/GSL/files/4147555/build.log) from the attempt to build following sample cmake project: [test.zip](https://github.com/microsoft/GSL/files/4147570/test.zip).

Problem seems to be caused by the directive that requests treating gsl's include directory as system header directory: https://github.com/microsoft/GSL/blob/master/CMakeLists.txt#L62 when GSL is not being build as standalone project.

**Comment by AntonioND** [comment] 2020-03-12 16:56
I have the same problem.

It looks like the problem is the ``-isystem`` directive of GCC in Arm:

https://github.com/conan-io/conan/issues/269#issuecomment-220654579

Turning this:
``target_include_directories(GSL SYSTEM INTERFACE``
into this:
``target_include_directories(GSL INTERFACE``
fixes it.

Maybe this can be a build option that can be turned off? Or just make it never use ``SYSTEM``?

**Comment by zaq32** [comment] 2020-03-18 10:38
`Or just make it never use SYSTEM?`
That would be my suggestion as well but it was marked as `SYSTEM` in a first place to suppress warnings from gsl headers and that was change requested more than once already
* https://github.com/microsoft/GSL/pull/731
* https://github.com/microsoft/GSL/pull/465

Anyway this issue prevents me from using recent gsl version without forking it.

**Comment by AntonioND** [comment] 2020-03-18 10:44
Then I guess that the right thing to do is to have a build option that can disable the ``SYSTEM`` keyword. To be fair, I don't think this is a bug here or in CMake, but in GCC. That doesn't change the fact that we need a workaround...

**Comment by hsutter** [comment] 2020-10-28 22:55
Maintainers' call: This was fixed in #731 but we forgot to close this issue. If there's still a problem please let us know. Thanks!

**Closed by hsutter** 2020-10-28 22:55 UTC
