### ISSUE TITLE
GSL as sub-project

### ISSUE THREAD

**Issue by sezaru** [Microsoft/GSL#363] opened 2016-09-16 17:17 UTC
Currently gsl's CmakeLists.txt doesn't support it's addition as a sub-project from another cmake project, is that by design?

If not, adding something like this:

```
add_library(${PROJECT_NAME} INTERFACE)

target_include_directories(${PROJECT_NAME} INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/gsl)
```

would make it possible to simply using gsl as follow:

```
add_subdirectory(GSL);

target_link_libraries(${PROJECT_NAME} GSL)
```

**Comment by MikeGitb** [comment] 2016-09-16 20:16
Just in case this is not clear: 
As this is a header only library, there is nothing you have to build and link to. The cpp files in this repo are just tests. The only thing you have to do to include the gsl in your project is to copy the gsl folder and add the folder to your include paths.

**Comment by sezaru** [comment] 2016-09-16 21:59
I know that, but this means that I need to copy the folder to my project and losing the source control. so every time I want to update to the master of gsl repository, I would need to clone it and copy it again..

These changes make possible that I can only add the gsl repository as a submodule to my project and keep it updated.

Note that this create a interface library, it will not create a real library (since it doesn't have cpp files).

**Comment by MikeGitb** [comment] 2016-09-17 05:31
Maybe I'm missing something, but you can already clone the gsl into a subfolder of your project and add `include_directories(<path-to-repo>)` to your cmake file to use it, no?
I'm not opposed to the change, just trying to understand what the difference is.

**Comment by godbyk** [comment] 2016-09-17 06:18
@MikeGitb The [interface library](https://cmake.org/cmake/help/v3.5/manual/cmake-buildsystem.7.html#interface-libraries) method is the more modern way to do it. It's more flexible as you can set GSL-specific preprocessor definitions, compiler flags, etc. that will be included automatically whenever you use `target_link_library(MyTarget GSL)`.

Conversely, using the `include_directories()` approach has a couple drawbacks: (1) `include_directories()` is global to the entire project (though you could work around this easily enough with `target_include_directories()`, and (2) if using GSL entails any additional compiler flags and the like, the programmer would have to know about them and add them to each and every target that relies on GSL. If GSL provides an interface library, this is handled automatically.

**Comment by neilmacintosh** [comment] 2016-09-19 18:52
@sezaru to answer the original question, no, it's not by design. We simply built the CMake file as a way of building and running the test suite relatively easily.

I'd be very happy to look at a PR if this small change would leave the existing functionality unchanged but make the library easier to consume in CMake environments.

**Comment by sezaru** [comment] 2016-09-20 14:28
Done [#370](https://github.com/Microsoft/GSL/pull/370) :)

**Comment by WillEwing** [comment] 2017-02-01 23:50
I would suggest exporting the interface library target during installation, creating a `cppgsl-config.cmake` and `cppgsl-targets.cmake` file in...  appropriate locations in the installation directory.  

I would suggest calling it `cppgsl` because `find_package(GSL)` will cause CMake to search for GNU Scientific Library.  The CMake project name and library target would also have to be renamed as well to avoid the conflict.

**Comment by neilmacintosh** [comment] 2017-04-26 00:24
I think this has been obsoleted by PR #493 which creates a header-only library target for the GSL.

**Closed by neilmacintosh** 2017-04-26 00:24 UTC
Labels: resolved
