### ISSUE TITLE
array_view should delete contructors taking expiring values

### ISSUE THREAD

**Issue by gdr-at-ms** [Microsoft/GSL#138] opened 2015-10-10 18:15 UTC
Add constructors taking `&&` and delete them.

**Comment by mattnewport** [comment] 2015-10-10 18:19
Are you suggesting this should not be valid code?
```C++
vector<int> f();
void g(array_view<int> x);
g(f());
```
Please no! That is even worse than not having an `array_view` constructor from `std::initializer_list` :-1:

**Comment by mattnewport** [comment] 2015-10-10 18:25
This would also have the highly undesirable effect that you could not take an existing function that takes a `vector` argument by const ref and make it more general by changing the argument to take an `array_view` without breaking any calling code that passed a temporary.

**Comment by gdr-at-ms** [comment] 2015-10-10 18:25
The suggestion is to make the expected lifetime explicit.  See the lifetime paper.  You can't achieve those guarantees if you fall for "convenience".

**Comment by neilmacintosh** [comment] 2015-10-10 18:26
Exactly. I agree with @gdr-at-ms  here. Those constructors may seem convenient but increase the likelihood of writing code that is unsafe-by-construction.

**Comment by mattnewport** [comment] 2015-10-10 18:26
Do you have a link or paper number for the lifetime paper?

**Comment by gdr-at-ms** [comment] 2015-10-10 18:29
See:
https://github.com/isocpp/CppCoreGuidelines/blob/master/docs/Lifetimes%20I%20and%20II%20-%20v0.9.1.pdf
https://github.com/isocpp/CppCoreGuidelines/blob/master/docs/Introduction%20to%20type%20and%20resource%20safety.pdf

**Comment by gdr-at-ms** [comment] 2015-10-10 18:51
Unfortunately, I think the lifetime paper is something that needs careful reading, not just skimming or jump-reading.  Herb and Neil did a very good at giving an overall view in this talk: https://www.youtube.com/watch?v=hEx5DNLWGgA%5D

If that still does not satisfy you, I am afraid you would have to wait for the more wonkish, greek letter version to come out (still in the work.)

**Comment by mattnewport** [comment] 2015-10-10 18:59
@gdr-at-ms @neilmacintosh 
I really think you should reconsider this. Consider a bug free existing codebase with functions `void f(const std::vector<int>&)` and `std::vector<int> g()` which has lots of perfectly safe and valid code like `f(g())`. I should be able to switch the definition of `f()` to `void f(std::array_view<const int>)` and recompile without changing all of the calling code to the hideous `auto v = g(); f(v);`.

**Comment by mattnewport** [comment] 2015-10-10 19:06
@gdr-at-ms @neilmacintosh 
Just to be more explicit about the constructor issue:
```C++
vector<int> g();
struct Foo { Foo(const vector<int>& v); };
struct Bar { Bar() foo{g()} {}; Foo foo; };
```
Now how do I switch Foo to 
```C++
struct Foo { Foo(array_view<const int> av); };
```

**Comment by gdr-at-ms** [comment] 2015-10-10 19:06
We hear you.  There are many important variables in this project requiring balancing acts.

I hope people embracing this project go after codes that they suspect are unsafe and rout out the sources of unsafety first, adding concrete tangible value; or adopt the practice in new projects. Just polishing the part that they are already safe brings less value.

**Comment by tamaskenez** [comment] 2015-10-10 20:55
I think Eric Niebler's reasoning in [D4128 section 3.3.2](https://ericniebler.github.io/std/wg21/D4128.html#ranges-cannot-own-elements) applies here as well.
In his terminology, `array_view` is a Range and section 3.3.2 explains why it's a bad idea to construct a Range on an rvalue Container.

**Comment by neilmacintosh** [comment] 2015-10-10 21:09
Accidentally closed this (that big button is more attractive to my mouse than the smaller "Comment" one sometimes). I agree wholeheartedly with @gdr-at-ms 's original sentiment. And yes, Eric has a nice illustration of the risks of allowing these constructors on view-like types.

**Comment by mattnewport** [comment] 2015-10-10 21:14
@neilmacintosh 
This is a deal breaker for me on adopting `array_view`. If `f(g())` is not a valid usage of `array_view` then I'll create my own version for use in my projects. I'd really like to have a usable standard `array_view` but this restriction makes it unusable for my purposes.

The constructor issue I highlight above is a big one IMO. What is your suggested workaround there?

**Comment by mattnewport** [comment] 2015-10-10 22:01
@neilmacintosh @gdr-at-ms 
Another comment on this issue: as I understand it the intent is for the compiler and static analyzer tools to have an understanding of `array_view`. In that case it seems like broken uses like
```C++
vector<int> g();
auto av1 = array_view<int>{{1, 2, 3, 4}};
auto av2 = array_view<int>{vector<int>{1, 2, 3, 4}};
auto av3 = array_view<int>{g()};
```
Are ideal cases for static analysis tools to catch (in increasing order of difficulty to implement I imagine).

There shouldn't be a need to use overly broad tool of deleting && constructors to catch these cases while still allowing highly desirable and perfectly valid uses like:
```C++
void f(array_view<int>);
vector<int> g();
f(g());
f({1, 2, 3, 4});
```

**Comment by gdr-at-ms** [comment] 2015-10-10 23:10
I take this as feedback for clarifying what it is we are aiming at with the C++ Core Guidelines and its support library (GSL).  It is a long educational journey and we just started.

**Comment by Horstling** [comment] 2015-10-11 19:27
How will the static analyzer handle cases like this?

    struct foo
    {
    	void take(const std::vector<int>& v)
    	{
	    	m_v = &v;
	    }
	
    	const std::vector<int>* m_v;
    };

    foo f;
    f.take({1, 2, 3});
    // f.m_v is now dangling

If the analyzer is able to catch the dangling pointer, there is no reason to forbid views to temporaries; every unsafe use of this feature should be catched by the analyzer, just like it does for references.

The core guidelines document classifies ranges and views as non-owning "Pointer", together with raw pointer and references. So why shouldn't a view behave just like a reference?

**Comment by neilmacintosh** [comment] 2015-10-11 20:37
It's great to catch the error with tooling. It's even better to prevent unsafe code from being compiled in the first place. Asking people to make the lifetimes of objects explicit and correct is in line with the overall goals of the Core Guidelines and GSL. The issue is accepted and will be implemented.

**Comment by Horstling** [comment] 2015-10-11 22:00
Well in this case you should also add the rule "Don't bind temporaries to references" to the guidelines and enforce it by the static analysis. Otherwise you have some inconsistency here.

**Comment by mattnewport** [comment] 2015-10-11 22:21
@Horstling 
Except the language [guarantees](http://stackoverflow.com/questions/2784262/does-a-const-reference-prolong-the-life-of-a-temporary) that local const references extend the lifetime of a temporary. This is perfectly safe:
```C++
const auto& x = {1, 2, 3, 4};
// lifetime of temporary initializer_list extended to the scope of x
```
But this is not transitive through function arguments which is why this would not be safe (if array_view supported it):
```C++
auto av = array_view<int>{{1, 2, 3, 4}};
```

**Comment by mattnewport** [comment] 2015-10-11 23:01
I think I have a workaround for if I have to use an `array_view` with deleted `&&` constructors:
```C++
template<typename T>
array_view<std::add_const_t<T>> av(const std::initializer_list<T>& x) { return {std::begin(x), x.size()}; }

template<typename C>
array_view<std::add_const_t<typename C::value_type>> av(const C& x) { return {x}; }

int main() {
    printFirst(av({1, 2, 3}));
    printFirst(av(std::vector<int>{1, 2, 3}));
}
```
This is not perfect since while it enables `f(av(g()))`, `f(av({1, 2, 3}))` and Foo() : bar{av(g())} {}` it still requires going and changing the code at the call site for any such code if making a function more general by changing a function signature from, say `void h(const std::vector<int>&)` to `void h(gsl::array_view<const int>)`. A helper overload `void h(const std::vector<int>& x) { h(gsl::array_view{x}); }` can handle that case without changing the call site however so it's not as painful as I initially feared.

**Comment by Horstling** [comment] 2015-10-12 06:15
@mattnewport
You are right about the lifetime extension (Interestingly enough, in terms of the core guidelines this would be some kind of "owning reference"), but this is not the 99% use case of binding temporaries to references that I am talking about.

My point is: If the GSL bans code like this because it is "unsafe":

    void foo(gsl::array_view<int>);

    foo({1, 2, 3});

Than why should the guidelines allow code like this:

    void foo(const std::vector<int>&);

    foo({1, 2, 3});

Both function are getting called with a (semantical) reference to a temporary; in both cases the original data will be gone as soon as the function returns, in both cases the called code as no chance to know about this.

I think the GSL / the guidelines should either support both (which I prefer) or ban both (which would be consistent).

**Comment by mattnewport** [comment] 2015-10-12 06:33
@Horstling 
I agree this is an inconsistency. I think `array_view` banning constructors taking `&&` is inconsistent with the language as a whole. My workaround functions above highlight this I think - the language is very clear that binding a temporary / rvalue to a const reference is perfectly fine (for very good reasons) which is why there is no need for any casting to bypass the deleted `&&` constructors in my `av()` helper above. 

It's quite clear that these are all perfectly safe, valid and good C++:
```C++
vector<int> f();
void g(const vector<int>&);
void h(std::initializer_list<int>);
g(f());
g({1, 2, 3});
h({1, 2, 3});
```
And it seems quite natural to generalize `g()` to:
```C++
void g(array_view<const int>);
```
And to be able to call it (safely) like:
```C++
g(f());
g({1, 2, 3});
```
The only problem is that this as a side effect enables the unsafe:
```C++
auto av = array_view<const int>{{1, 2, 3}};
auto av = array_view<const int>{f()};
```
But there are plenty of other ways to use `array_view` unsafely that preventing the good uses above can't solve. You're going to need static analysis anyway (and that's already part of the plan) so why fight the fact that at the language level C++ doesn't provide a way to enforce this kind of safety in all cases.

**Comment by gdr-at-ms** [comment] 2015-10-12 06:39
@Horstling 
The Core Guidelines and the GSL don't ban
```
void foo(gsl::array_view<int>);
```
This specific issue isn't even about that.

**Comment by Horstling** [comment] 2015-10-12 06:51
@gdr-at-ms 
Ofc you don't ban the function declaration, but you ban calling the function with temporaries.

**Comment by gdr-at-ms** [comment] 2015-10-12 06:58
Still not correct.  You can call such a function with temporary `array_view` objects.

**Comment by Horstling** [comment] 2015-10-12 07:14
Ok, let`s try it again. What are the reasons for banning this kind of calls:

    void foo(gsl::array_view<int>);
    std::vector<int> bar();

    foo({1, 2, 3}); // <-- this one
    foo(bar()); // <-- or this one

And why do these reasons do not apply for references?

    void foo(const std::vector<int>&);
    std::vector<int> bar();

    foo({1, 2, 3});
    foo(bar());

**Comment by gdr-at-ms** [comment] 2015-10-12 11:22
@Horstling 
See previous comments.

**Comment by Horstling** [comment] 2015-10-12 13:17
I only see comments about how you think constructing a `array_view` from a temporary is unsafe. I do not see a single word about binding a temporary to a reference. How about just answering this very simple questions:

Do you think it is unsafe to pass temporaries to functions that take const& ?

If your answer is **no**:

- What is the big difference between an `array_view` and a reference that passing a temporary to a function that takes an `array_view` becomes unsafe?

If your answer is **yes**:

- Why don`t the guidelines ban this kind of unsafe code?

**Comment by gdr-at-ms** [comment] 2015-10-12 13:52
@Horstling 
More specifically, the statement is that an `array_view` constructor that takes a `&&` is unsafe because it is storing a reference to an expiring object and there is no indication of what the lifetime of the resulting `array_view` object is.  If you can make the lifetime of the object explicitly related to input container, you would make it safe.

**Comment by Horstling** [comment] 2015-10-12 14:12
@gdr-at-ms 
And again you are ignoring the comparison to references.

    void foo(const std::vector<int>&);

    // here I'm binding an expiring object to a reference
    foo({1, 2, 3});

    void foo(const std::vector<int>&)
    {
        // here I have no indication of what the lifetime of the referred object is
    }

So how is this any different from passing a temporary container to a function through an `array_view` object?

`array_view` is just another form of reference, so why would you use a different set of rules to decide wheter code is safe or unsafe?

**Comment by gdr-at-ms** [comment] 2015-10-12 14:47
I am not ignoring the comparison with const references.  We are dealing with them, as I indicated.

**Comment by neilmacintosh** [comment] 2015-10-12 15:12
@Horstling, @mattnewport, @gdr-at-ms 

 think this thread is pretty much dead. I have already indicated that I have accepted the issue and will be deleting the && constructors on `array_view`. I appreciate the constructive and informative discussion up to this point, but I think now we are just starting to circle back around the same arguments.

To summarize: there have already been a number of replies on this thread that have made the reasoning on this issue clear. Binding an `array_view` to the contents of a temporary in its constructor is not a safe practice - it encourages code that is fragile. This reasoning should not be terribly shocking. As an earlier post pointed out, Eric Niebler's ranges proposal employs much the same reasoning about && constructors. Yes, this decision means that some syntactic convenience around binding a temporary `array_view` to a temporary container resulting from the return of a function call will be unavailable.

The overall aim of the Core Guidelines and GSL is to encourage better quality code by-construction - to avoid practices that make code brittle like binding an object to another that is a temporary. `array_view` is part of that broader project and so will reflect those aims. There may be existing language constructs or classes that do not follow these principles already. That is not justification for failing to apply the principles here.

**Closed** 2015-10-12 15:20 UTC
Labels: open
