### ISSUE TITLE
rename Final_action to final_action

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#100] opened 2015-09-29 17:26 UTC
My PR for this change got merged into the guidelines by gdr, so we should make the corresponding change here.

**Comment by neilmacintosh** [comment] 2015-09-29 19:56
Closing as a duplicate of #91. Would you like to submit a PR that makes the change linked to that issue?

**Closed by neilmacintosh** 2015-09-29 19:56 UTC
Labels: duplicate

**Comment by trebconnell** [comment] 2015-09-29 20:12
I won't be have time til Thursday
