### ISSUE TITLE
seeing max as the macro max(a,b)

### ISSUE THREAD

**Issue by Lukapone** [Microsoft/GSL#156] opened 2015-10-20 21:22 UTC
When I compiled the headers with Visual studio 2015 I got : 
                                                                        error C2589: '(' : illegal token on right side of '::'
                                                                        error C2059: syntax error : '::'

Simple solution at: http://stackoverflow.com/questions/1904635/warning-c4003-and-errors-c2589-and-c2059-on-x-stdnumeric-limitsintmax

**Comment by neilmacintosh** [comment] 2015-10-20 21:25
Yes, this is a known issue with some sequences of inclusions. See #142 for another instance. I'll resolve this as a duplicate of that issue and we can explicitly guard against those macros for the MSFT compilers.

**Closed by neilmacintosh** 2015-10-20 21:25 UTC
