### ISSUE TITLE
CMakeLists.txt tinkers with CXX_STANDARD

### ISSUE THREAD

**Issue by higaski** [microsoft/GSL#901] opened 2020-07-26 19:25 UTC
Including GSL with CMakes gives me some weird behavior regarding the set CXX_STANDARD.

I'm currently running CMake 3.17.3 and include GSL in a little toy project like this:
```
FetchContent_Declare(GSL GIT_REPOSITORY https://github.com/microsoft/GSL.git)
FetchContent_MakeAvailable(GSL)+
target_link_libraries(EmscriptenExample PRIVATE GSL)
```

My targets own CXX_STANDARD should get set to C++20 by using target_compile_features:
`target_compile_features(EmscriptenExample PUBLIC cxx_std_20)`

Now things get weird. When I compile the project with a Clang toolchain file I get the following output:
`/usr/bin/clang++   -isystem _deps/gsl-src/include -std=c++2a -std=gnu++2a`
So apparently CMake adds -std=c++2a just as I wished but then GSL overwrites the standard to use -std=gnu++2a instead? How the hell did that happen? I've checked the CMakeLists.txt file and there's even a comment saying that extensions are forced off...

Now, as the target name already revealed I'd also like to use the Emscripten toolchain to compile to WebAssembly. When I compile the project with Emscriptens very own toolchain file I get the following output:
`/usr/lib/emscripten/em++   -isystem _deps/gsl-src/include -std=c++2a -std=gnu++14`
And now I'm completely lost. This also results in a compiler error on my end since I'm already using C++17 and 20 features...

Any suggestions?

/edit
Upon further investigation I'd say that this is an Emscripten bug. For some reason CMakes cxx_std_XX feature flags don't seem to work with this toolchain. As a temporary workaround I'm now passing -DCMAKE_CXX_STANDARD:STRING=20 to CMake on the command line.

**Comment by JordanMaples** [comment] 2020-08-05 19:57
Closing since @higaski noted that this issue appears to be caused by Emscripten. Please reopen if you find that the issue is caused by GSL.

**Closed by JordanMaples** 2020-08-05 19:57 UTC
