### ISSUE TITLE
System `#include` namespace for GSL?

### ISSUE THREAD

**Issue by galik** [Microsoft/GSL#277] opened 2016-03-25 11:01 UTC
I am going to suggest renaming the headers folder from `include` to, well just about anything else but something like `ccgsl` and here is why.

I think the library would benefit from choosing a, *include* namespace so developers can start including `GSL` modules in a manner that is less likely to conflict with other projects. Simply putting the headers in `include` increases the likelihood of future clashes when compiling against a *system installed* version of `GSL` eg:

```cpp
#include <span.h> // could clash with a million other libraries
```

Often a library will put their headers in a project sub-folder of the system `include`, for example:

```cpp
#include <SFML/Audio.hpp>
```

But even when the `GSL` is not installed system-wide and in its developmental form it would be good to still include its headers using such a standard include format by simply setting the *include path* for the compiler. So if I store the development version f `GSL` here:

```cpp
/home/galik/dev/MS-GSL
```

Well currently my choices are:

**A)** Set compiler to `-I$(HOME)/dev/MS-GSL/include` and do `#include <span.h>` ...

**B)** Set compiler to `-I$(HOME)/dev/MS-GSL` and do `#include <include/span.h>` ...

Neither of those are really satisfactory for me. So I do some sym-link shenanigans and fudge everything to look like a local copy where I just do:

```cpp
#include "gsl/span.h"
```

This is why I would suggest to change the name of the folder that the `GSL` lives in from `include` to `gsl`.

**EXCEPT!!!**

As was pointed out a while ago, there is a name-clash with another major project that goes by the name "GSL" [GNU Scientific Library](https://www.gnu.org/software/gsl/).

Those of us who have that installed as a system library are already doing this:

```cpp
#include <gsl/...>
```

So putting *this* `GSL` the same place as the *other* `GSL` is a bit problematic.

So I would suggest something a little more unique like `ccg-gsl` or `ccgsl` for "C++ Core Guideline-Guideline Support Library" and "C++ Core Guideline Support Library" respectively (or something else IDK).

Then I can do:

```cpp
#include <ccgsl/span.h> // and be a happy bunny
```

Does this make sense?

**Comment by neilmacintosh** [comment] 2016-08-03 18:21
Hi @galik! I like this idea and it makes a lot of sense. As a first step in this direction I've merged #207 which means there is now an "install" target in the CMake files which will install to a gsl subdirectory.

I'd be happy to look at a pull request if you've got the time to put one together.

I'm not sold on the name-uniqueness issue. I think "gsl" would be fine as a prefix, and for people who happen to use both this library and the scientific GSL, there will need to be some disambiguation work anyway.

**Comment by galik** [comment] 2016-08-04 13:07
Hi, I created a PR that just renames the library folder to `gsl` allowing for `#include <gsl/span.h>` across the board.

**Comment by galik** [comment] 2016-08-09 14:38
Finally! Not sure what the previous problem was, maybe something I did with the `unittest-cpp` submodule?

**Comment by neilmacintosh** [comment] 2016-08-10 00:58
Thanks @galik for PR #317 that addressed this issue. I'll close this out now.

**Closed by neilmacintosh** 2016-08-10 00:58 UTC
Labels: resolved

**Comment by omeid** [comment] 2018-06-19 16:33
@galik Why did you make it `gsl` when the suggestion was `ccgsl`? How do I install this now along with `gsl`?

**Comment by galik** [comment] 2018-06-19 16:58
@omeid It was not my decision what the name of the directory would be. My interest in this patch was simply to *have* a named subdirectory. The fact is `gsl` was not the choice I would have made.

At the end of the day when `Linux` distros start adding this to their distribution they will have to make a patch to rename the folders and possible other things. I don't see any `Linux` distribution installing this library into the same place where `GNU GSL` lives.

Currently I use a copy installed in my home directories. But now there is versioning I too am probably going to have to think about where to put it in the system namespace for headers. I'll probably just add a subdirectory to show this is a `Microsoft` implementation. Something like `/usr/include/microsoft/gsl-1.0/gsl` as there are other implementations out there.

**Comment by omeid** [comment] 2018-06-20 01:49
> At the end of the day when Linux distros start adding this to their distribution they will have to make a patch to rename the folders and possible other things.

This will create inconsistency, I can't simply publish my code and expect it will work for everyone else, without them having to fiddle with include paths.


> I don't see any Linux distribution installing this library into the same place where GNU GSL lives.

If you install `microsoft-gsl` in Archlinux, this is exactly what happens. :(

**Comment by galik** [comment] 2018-06-20 02:06
> This will create inconsistency, I can't simply publish my code and expect it will work for everyone else, without them having to fiddle with include paths.

You usually can. Different `Linux` distros store things in different places. Usually there is a software way to discover their location. Many projects use `pkg-config`. It tells you where to find the headers and the libraries for a given project.  

I started working on a patch for installing to a `Linux System` but I'm not sure how to use `CMake` so I may not have done things the best way.

I made a branch from release `GSL v1.0.0` where I modified the `CMakeLists.txt` and added a `ms-gsl.pc.in` config file for `pkg-config`. If you look in those you should be able to see what I did (its only a couple of minor edits):

https://github.com/galik/GSL/tree/linux_patch-v1.0.0

I am fairly sure a while ago I saw a `PR` somewhere where someone had already added a `pkg-config` config file but I was unable to locate it.

> If you install microsoft-gsl in Archlinux, this is exactly what happens. :(

Has `Arch Linux` created an official package that does that? Or is that just what happens if you run the current installer?

**Comment by omeid** [comment] 2018-06-24 06:32
Also [happens with the installer](https://github.com/Microsoft/GSL/blob/master/CMakeLists.txt#L76).

**Comment by akstrfn** [comment] 2018-06-24 15:53
I packaged the aur package and I don't think that pkgconfig will solve the problem.

Lets say you use pkgconfig to point to include directories, ``#include <gsl/something>`` is still ambiguous. For the sake of example lets say that GNU-GSL adds ``gsl/span`` and that you use MS-GSL and GNU-GSL what happens when you call ``#include <gsl/span>``? AFAIK it will depend on the order of inclusions. Luckily GNU-GSL is a C library so they use "namespaces" in filenames hence all headers are prepended with gsl.

**Comment by omeid** [comment] 2018-06-25 05:36
In our project, we have opted against using GSL because we can make it work consistently across platforms at the moment, and the lack of interest from Microsoft GSM to avoid conflicts means they might break or interact with other libraries in the wrong way, so not worth the headache.

Thanks for looking into this @galik.

**Comment by galik** [comment] 2018-06-25 17:05
@omeid Whilst this is definitely a problem that `Linux` maintainers will have to sort out, for individual projects you don't need to use system installed versions. This implementation comes with a friendly license (MIT I believe). That means you can copy the  `MS-GSL` headers directly into your project's source folders and distribute them along with your project source. By putting them into your project source tree you always know exactly where to find them whichever system you are compiling on. There is still a bit of a problem using the GNU GSL in the same project though.

**Comment by omeid** [comment] 2018-06-27 01:07
I appreciate your suggestions. But as you said, there is a bit of problem when using it with GNU Scientific Library, which we are, and while it kind of works, it is very confusing and a breakage waiting to happen.

While it is true that now the burden of cleaning this mess is on package maintainers, the problem is that _inconsistencies_ in how it is fixed are bound to happen.

Bottom line is, there is questionable value in making a somewhat optional  and _non-critical_ library a _hard_ dependency throughout your code when the library developers do not consider interoperability with the ecosystem that much of a deal.
