### ISSUE TITLE
There is no information on ABI compatibility

### ISSUE THREAD

**Issue by realnc** [microsoft/GSL#647] opened 2018-03-24 14:07 UTC
It is not clear whether the GSL is suitable for use in library APIs. When using it in libraries that need to provide a stable ABI, it is not clear whether an update to GSL would break the ABI of the library:

    // Will this break the ABI in the future?
    void public_func(gsl::not_null<int*> ptr);

It would be helpful if the documentation mentioned whether the GSL provides any ABI compatibility guarantees.

**Comment by annagrin** [comment] 2018-06-15 19:37
@realnc Could you please elaborate on API compatibility? Versions will mark when API break (according to semantic versioning scheme).

ABI compatibility is not entirely in GSL hands. For example, gsl::span was designed intentionally for use on binary boundaries. There is no official guarantee by MS compiler (not sure about others) that it will be stable, but those mangled names have been stable de-facto for many years, AFAIK.  For all practical purposes they are stable (as in if they break the world ends anyway, or at least requires total recompilation:)

@MikeGitb I've started versioning - stable versions (the commits I have extra verification on) are marked according to the semantic versioning, so commits between them can be regarded as work towards the next version (i.e. not stable). I will appreciate any suggestions here to make versioning clear. Versioning every commit that breaks API will be a little noisy.

**Comment by johelegp** [comment] 2018-06-15 20:07
According to [SemVer](https://semver.org/):
1) [The public API must be declared.](https://semver.org/#spec-item-1) What should we rely on about this? Right now, the answer seems to be the code itself. Even then, that needs to be explicitly declared. After we know what the public API is, [semantic versioning becomes useful](https://semver.org/#spec-item-5).
2) It'd be nice if it was declared that GSL uses Semantic Versioning, according to the last paragraph [here](https://semver.org/#why-use-semantic-versioning).

**Comment by MikeGitb** [comment] 2018-06-15 20:10
@annagrin: Having releases that receive special testing is imho a very good step. 

ABI/API stability usually means that you don't make api braking changes for some time (i.e. it doesn't help anyone, if you apply correct semantic versioning, but publish a "major" release every few month that makes some API or ABI breaking changes and don't apply bugfixes for older releases).

**Comment by realnc** [comment] 2018-06-15 20:42
@annagrin 

> Could you please elaborate on API compatibility? Versions will mark when API break (according to semantic versioning scheme).

What I'm asking about is the ability to update to a new GSL version in a library that is supposed to be ABI compatible with prior releases. If a library that uses GSL is installed as `/usr/lib/libFoo.so`, and then a new version is released, all existing binaries on the system that link against `/usr/lib/libFoo.so` will use the new version.

If I don't use the GSL in my library's public API, I can easily guarantee ABI compatibility. If I do use the GSL however, it's not easy to tell whether I can use a new GSL version or not in new versions of my library. I would have to keep using the same GSL version for years to come, or bite the bullet and only guarantee API stability instead of ABI stability.

What you usually get with C++ libraries is ABI compatibility for minor version updates. When using Qt for example, all your software that is linking against /usr/lib/libQt5Gui.so.5 will continue to work as you update your Qt installation from 5.6 to 5.7 to 5.8, etc. This is something guaranteed and documented by the Qt library. Some libraries do not provide ABI compatibility between minor version updates, and they document that fact.

The GSL does not document it at all, so we basically don't know if it's safe or not to update to a new GSL version next year, or whether we need to stick to the old version we used the first time.

**Comment by hsutter** [comment] 2020-11-11 23:30
Maintainers' call: The GSL does not currently support ABI stability across binary/link boundaries other than the usual for C++ types, which is that need to compile both caller and callee with compatible compilers and switch settings. However, it is a goal that we have in mind for the future. In the meantime we'll close this though because we don't have a timeline for when we will be able to consider giving these guarantees.

**Closed by hsutter** 2020-11-11 23:30 UTC
